Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"  # Or your specific box
  config.vm.network "private_network", ip: "192.168.56.100"

  # Specify the VirtualBox provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4048"  # Set RAM to 2GB
    vb.cpus = 3         # Set CPU cores to 2
  end
end