Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  
  # Define the nginx VM
  config.vm.define "nginx" do |nginx|
    # Customizing the VM
    nginx.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"  # Set RAM to 2 GB
      vb.cpus = 2         # Set CPU to 1
    end

    # Network configuration
    nginx.vm.network "private_network", ip: "10.0.0.20"

    # Provisioning NGINX (without modifying config file)
    nginx.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y nginx
    SHELL
  end
end
